// Flat config (ESLint 10+). See https://eslint.org/docs/latest/use/configure/configuration-files
import js from "@eslint/js";
import tseslint from "typescript-eslint";

export default tseslint.config(
  // src/lib/api/schema.d.ts is regenerated by openapi-typescript (see
  // frontend/src/lib/api/CLAUDE.md) — linting it would just fight the codegen.
  {
    ignores: ["dist", "node_modules", "*.config.js", "*.config.ts", "src/lib/api/schema.d.ts"],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
    },
  },
);
