// Tiny typed fetch helper shared by the hand-written hooks in this folder
// (Session 6 — Frontend upload + outline UI).
//
// We deliberately do *not* pull in `openapi-fetch`: the surface area is two
// POST routes, and the schema types generated by `openapi-typescript` into
// `schema.d.ts` are enough to type the request/response by hand. One fewer dep
// to vet under §6.7, one less tool that could collide with the project's
// `typescript@6.0.3` peer-conflict territory.
//
// `ApiError` carries the HTTP status and the backend's `ErrorResponse.detail`
// so hooks can discriminate failure modes (400 / 404 / 409 / 413 / 415 / 502)
// by status code — never by string-matching the message. Callers that need to
// distinguish FastAPI's `HTTPValidationError` (422 with `detail: ValidationError[]`)
// from an explicit `HTTPException(status_code=422, detail=str)` should read
// `err.body` (the raw parsed JSON) and branch on its shape; see the cross-cutting
// 422-overload note in docs/PLAN_SHORT.md.

/**
 * Base URL for backend API calls. Defaults to the dev backend on
 * `http://localhost:8000`; override per-environment with `VITE_API_BASE_URL`.
 * CORS on the backend is strict — see `frontend/CLAUDE.md`.
 */
export const API_BASE_URL: string = import.meta.env.VITE_API_BASE_URL ?? "http://localhost:8000";

/** Thrown for any non-2xx response from the API. */
export class ApiError extends Error {
  readonly status: number;
  readonly detail: string;
  /**
   * Raw parsed body, when JSON. Use this when the message string isn't enough
   * and you need the structured form (e.g. `HTTPValidationError.detail[]`).
   */
  readonly body: unknown;

  constructor(status: number, detail: string, body: unknown) {
    super(`${status}: ${detail}`);
    this.name = "ApiError";
    this.status = status;
    this.detail = detail;
    this.body = body;
  }
}

/** POST a `FormData` body to `path` and parse the JSON response. */
export async function postFormJson<T>(path: string, body: FormData): Promise<T> {
  const response = await fetch(`${API_BASE_URL}${path}`, {
    method: "POST",
    body,
    // Intentionally no Content-Type header — the browser sets the correct
    // `multipart/form-data; boundary=...` from the FormData itself.
  });
  return readJson<T>(response);
}

/** GET `path` and parse the JSON response. */
export async function getJson<T>(path: string): Promise<T> {
  const response = await fetch(`${API_BASE_URL}${path}`, { method: "GET" });
  return readJson<T>(response);
}

/** POST an `application/json` body to `path` and parse the JSON response. */
export async function postJsonBody<T>(path: string, body: unknown): Promise<T> {
  const response = await fetch(`${API_BASE_URL}${path}`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body),
  });
  return readJson<T>(response);
}

async function readJson<T>(response: Response): Promise<T> {
  const text = await response.text();
  const body: unknown = text ? safeJsonParse(text) : null;
  if (!response.ok) {
    const detail = extractDetail(body) ?? (response.statusText || "request failed");
    throw new ApiError(response.status, detail, body);
  }
  return body as T;
}

function safeJsonParse(text: string): unknown {
  try {
    return JSON.parse(text);
  } catch {
    return text;
  }
}

/**
 * Pull a human-readable error string out of a parsed body. Handles both the
 * backend's `ErrorResponse` (`{detail: str}`) and FastAPI's auto-generated
 * `HTTPValidationError` (`{detail: ValidationError[]}` — joined with `; `).
 */
function extractDetail(body: unknown): string | null {
  if (typeof body !== "object" || body === null || !("detail" in body)) return null;
  const detail = (body as { detail: unknown }).detail;
  if (typeof detail === "string") return detail;
  if (Array.isArray(detail)) {
    const messages = detail
      .map((d) =>
        typeof d === "object" && d !== null && "msg" in d
          ? String((d as { msg: unknown }).msg)
          : "",
      )
      .filter(Boolean);
    return messages.join("; ") || "validation error";
  }
  return null;
}
