/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/stories/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Story */
        post: operations["upload_story_stories_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stories/{story_id}/structure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Structure Story
         * @description Build the document tree for a story (spec §7 step 2) and persist it.
         *
         *     Reads the story's stored raw text — which already carries the author's
         *     `##` / `###` anchors for manual/hybrid — builds the outline in the chosen
         *     mode, and inserts chapters → scenes → paragraphs. One-shot: the accept/edit
         *     loop is the frontend's job (Session 6). Re-structuring is refused (409) rather
         *     than silently appending a second tree.
         *
         *     Locking strategy: the outline is built *without* holding a DB write lock,
         *     because auto/hybrid awaits an LLM call that can take seconds. The story row
         *     is then `SELECT ... FOR UPDATE`-locked only for the small write window —
         *     re-check `list_chapters` under the lock, then insert. Two concurrent POSTs
         *     serialize on the lock: the second sees the persisted tree and 409s instead
         *     of duplicating.
         */
        post: operations["structure_story_stories__story_id__structure_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stories/{story_id}/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract Story
         * @description Extract + stage a story's candidates through the §3.3 cascade (spec §9 M3).
         *
         *     Walks every persisted paragraph, runs the ExtractionAgent, then the cascade, and *stages*
         *     each candidate with its proposal (NEW vs MERGE) — writing **nothing** to the graph
         *     (intercept-before-write, INV-9). The graph is written only when a human accepts at the
         *     review queue (`POST …/candidates/{id}/accept`, INV-1). The batch is resumable: if the
         *     router pauses on budget/quota, the run stops with `paused=true` (HTTP 202) and a re-POST
         *     continues from the first un-staged paragraph. Budget/quota are therefore *not* HTTP errors
         *     here by design (OQ-2); a hard agent failure maps to 502, a store outage to 503.
         */
        post: operations["extract_story_stories__story_id__extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stories/{story_id}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Story Graph
         * @description The story's entity graph for the read-only viewer (spec §3.4).
         *
         *     The graph is keyed by *project* (entities carry `project_id`, the §6.4
         *     multi-tenancy seam), so the route resolves the story to its project and returns
         *     that project's nodes/edges. No dedupe through M2 (INV-8) — the viewer renders
         *     whatever was written, duplicates and all, which is exactly the problem M3 solves.
         */
        get: operations["get_story_graph_stories__story_id__graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stories/{story_id}/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Entities Route
         * @description Search the project's accepted entities for the Stage-4 *manual handpick* (spec §3.3).
         *
         *     The reviewer can search **all** accepted entities in the project and pick any one as the
         *     merge target — the safety net for a true duplicate the deterministic cascade missed (a
         *     nickname embeddings don't catch, a name scoring just under threshold). Scope is the
         *     story's **project** (the §6.4 tenancy key); cross-project / "whole world" search is
         *     deferred with the §3.4 graph.
         *
         *     The query `q` is ranked **in Python** with the same RapidFuzz signal the matcher uses
         *     (`search_entities` over `canonical_name` + aliases) — so the human's search ≈ the
         *     machine's match — and so `q` **never reaches Cypher**: the only graph query
         *     (`list_entities`) is parameterised by `project_id` alone. Blank `q` → no results.
         */
        get: operations["search_entities_route_stories__story_id__entities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stories/{story_id}/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Candidates
         * @description The pending review queue for a story (spec §3.3 Stage 4) — candidates awaiting a human.
         */
        get: operations["list_candidates_stories__story_id__candidates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stories/{story_id}/candidates/{candidate_id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept Candidate
         * @description Commit a staged candidate to the graph — create a new entity or merge (spec §7 step 7).
         *
         *     This is the **only** graph-writing path (INV-1): the machine proposed, the human commits.
         */
        post: operations["accept_candidate_stories__story_id__candidates__candidate_id__accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stories/{story_id}/candidates/{candidate_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject Candidate
         * @description Reject a staged candidate — nothing enters the graph; the rejection is recorded.
         *
         *     The rejection is stored as evidence so a future matcher can consult it and not re-pester
         *     the author (DM-rej); that consult is not built in S4a.
         */
        post: operations["reject_candidate_stories__story_id__candidates__candidate_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/llm/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Llm Status
         * @description Today's spend, GPU-seconds, per-task-type breakdown, and the most recent call.
         */
        get: operations["llm_status_llm_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe used by the frontend smoke check and by CI.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AcceptRequest
         * @description The reviewer's decision (spec §3.3 Stage 4). All optional — defaults to the proposal.
         *
         *     `action` overrides the cascade's proposal (accept-as-merge / accept-as-create);
         *     `target_entity_id` retargets a merge (change-target); `custom_type` sets a type on create.
         */
        AcceptRequest: {
            /** Action */
            action?: ("create" | "merge") | null;
            /** Target Entity Id */
            target_entity_id?: string | null;
            /** Custom Type */
            custom_type?: string | null;
        };
        /** Body_upload_story_stories_upload_post */
        Body_upload_story_stories_upload_post: {
            /** File */
            file: string;
        };
        /**
         * CandidateView
         * @description One staged candidate for the §3.3 Stage-4 review queue (the render set S4b consumes).
         *
         *     Carries the quote/context (±200 chars), the cascade's NEW-vs-MERGE proposal + the stage it
         *     reached, the judge's reasoning (if Stage 3 ran), and the top-3 alternative entities the
         *     reviewer can retarget to. Persistence-only fields (the vector, project/story ids) are omitted.
         */
        CandidateView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Paragraph Id
             * Format: uuid
             */
            paragraph_id: string;
            /** Candidate Name */
            candidate_name: string;
            /** Type */
            type: string;
            /** Context */
            context: string;
            /**
             * Proposal
             * @enum {string}
             */
            proposal: "new" | "merge";
            /** Target Entity Id */
            target_entity_id: string | null;
            /** Stage Reached */
            stage_reached: number;
            /** Confidence */
            confidence: number | null;
            /** Reasoning */
            reasoning: string | null;
            /** Alternatives */
            alternatives: {
                [key: string]: unknown;
            }[];
        };
        /**
         * CandidatesResponse
         * @description A story's pending review queue.
         */
        CandidatesResponse: {
            /** Candidates */
            candidates: components["schemas"]["CandidateView"][];
        };
        /**
         * EntitySearchResponse
         * @description The handpick search hits, ranked best-first (spec §3.3 *Manual handpick*).
         */
        EntitySearchResponse: {
            /** Entities */
            entities: components["schemas"]["EntitySearchResult"][];
        };
        /**
         * EntitySearchResult
         * @description One accepted entity matched by the handpick search — the picker's row (M3.S4d).
         *
         *     Mirrors the review card's existing top-3 *alternative* shape (`entity_id` +
         *     `canonical_name` + `score`) so a picked search result feeds the same merge-accept path,
         *     plus `type` (to disambiguate same-named entities) and `aliases` (so the card can show
         *     *why* it matched). `canonical_name` is the project-language-resolved name the matcher
         *     ranks on, so the human's search reads the same name the machine matched.
         */
        EntitySearchResult: {
            /**
             * Entity Id
             * Format: uuid
             */
            entity_id: string;
            /** Canonical Name */
            canonical_name: string;
            /** Type */
            type: string;
            /** Score */
            score: number;
            /** Aliases */
            aliases: string[];
        };
        /**
         * ErrorResponse
         * @description Shape FastAPI's ``HTTPException`` produces — declared so the OpenAPI
         *     schema names every non-2xx response the routes can return, instead of just
         *     success + the auto-added 422 validation error. Without this, the generated
         *     TypeScript client (`frontend/src/lib/api/schema.d.ts`) can't model expected
         *     outcomes like 404 / 409 / 502 — leaving frontend error handling untyped.
         */
        ErrorResponse: {
            /** Detail */
            detail: string;
        };
        /**
         * ExtractResponse
         * @description Progress of an extraction run over a story's paragraphs (spec §9 M3).
         *
         *     Under intercept-before-write extraction *stages* candidates (it does not write the graph),
         *     so the count is `candidates_staged`, not entities/relations written. `paused` is the
         *     completion signal — true when the run stopped at the budget/quota pause-and-ask (HTTP 202,
         *     partial progress), false when it finished (HTTP 200). `paragraphs_done` counts paragraphs
         *     already staged (the resume checkpoint), so a re-POST resumes from the first not-done one.
         */
        ExtractResponse: {
            /**
             * Story Id
             * Format: uuid
             */
            story_id: string;
            /** Paragraphs Total */
            paragraphs_total: number;
            /** Paragraphs Done */
            paragraphs_done: number;
            /** Candidates Staged */
            candidates_staged: number;
            /** Paused */
            paused: boolean;
            /** Pause Reason */
            pause_reason: string | null;
        };
        /**
         * GraphEdge
         * @description One typed, directed relation for the viewer (edge label = `type`, §3.4).
         */
        GraphEdge: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Type */
            type: string;
            /**
             * Subject Id
             * Format: uuid
             */
            subject_id: string;
            /**
             * Object Id
             * Format: uuid
             */
            object_id: string;
            /** Confidence */
            confidence: number;
        };
        /**
         * GraphNode
         * @description One entity node for the §3.4 viewer — the display subset of `GraphEntity`.
         *
         *     Persistence-only fields (`properties`, `embedding`, `project_id`, `world_id`)
         *     are omitted: the read-only M2 viewer colours by `type`, labels by canonical
         *     name/aliases, and links each node to its first occurrence paragraph.
         */
        GraphNode: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Type */
            type: string;
            /** Canonical Name Pl */
            canonical_name_pl: string | null;
            /** Canonical Name En */
            canonical_name_en: string | null;
            /** Aliases */
            aliases: string[];
            /** First Seen Paragraph Id */
            first_seen_paragraph_id: string | null;
        };
        /**
         * GraphResponse
         * @description The story's knowledge graph as nodes + edges for the viewer.
         */
        GraphResponse: {
            /** Nodes */
            nodes: components["schemas"]["GraphNode"][];
            /** Edges */
            edges: components["schemas"]["GraphEdge"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LastCall
         * @description The most recently recorded call, for the §8.5 agent-activity panel ("which
         *     agent ran most recently, which model/tier, latency, cost"). System-derived,
         *     read straight from the latest ledger row; `created_at` is the store's clock.
         */
        LastCall: {
            /** Task Type */
            task_type: string;
            /**
             * Tier
             * @enum {string}
             */
            tier: "local_small" | "cloud_free" | "cloud_strong";
            /** Provider */
            provider: string;
            /** Model */
            model: string | null;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "success" | "refusal" | "failure";
            /** Latency Ms */
            latency_ms: number | null;
            /** Cost Estimate */
            cost_estimate: number | null;
            /** Gpu Seconds */
            gpu_seconds: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * LlmStatusResponse
         * @description Budget + today's usage + the most recent call, for the agent-activity panel.
         */
        LlmStatusResponse: {
            /** Daily Budget Usd */
            daily_budget_usd: number;
            /** Spent Today Usd */
            spent_today_usd: number;
            /** Remaining Usd */
            remaining_usd: number;
            /** Gpu Seconds Today */
            gpu_seconds_today: number;
            /** Calls Today */
            calls_today: number;
            /** By Task Type */
            by_task_type: components["schemas"]["TaskTypeUsage"][];
            last_call: components["schemas"]["LastCall"] | null;
        };
        /**
         * ReviewResponse
         * @description Outcome of an accept/reject: the committed entity (if any) + the terminal status.
         */
        ReviewResponse: {
            /**
             * Candidate Id
             * Format: uuid
             */
            candidate_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "created" | "merged" | "rejected";
            /** Entity Id */
            entity_id: string | null;
            /** Already Decided */
            already_decided: boolean;
        };
        /**
         * StoryUploadResponse
         * @description What the upload route returns once a story is persisted.
         *
         *     ``raw_text`` is echoed back so the frontend's manual-mode editor (spec §7
         *     step 2) has the parsed source to edit. The browser doesn't reliably parse
         *     .docx itself, so the upload response is the cheapest place to surface it;
         *     avoids a follow-up GET /stories/{id} round-trip that doesn't exist yet.
         */
        StoryUploadResponse: {
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /**
             * Story Id
             * Format: uuid
             */
            story_id: string;
            /** Title */
            title: string;
            /** Language */
            language: string;
            /** Paragraph Count */
            paragraph_count: number;
            /** Raw Text */
            raw_text: string;
        };
        /**
         * StructureRequestBody
         * @description Optional body for ``POST /stories/{id}/structure``.
         *
         *     When ``raw_text`` is provided, the route parses the outline from this payload
         *     instead of the story's stored copy AND persists it back to ``stories.raw_text``
         *     in the same transaction. This is how the frontend manual-mode editor
         *     (spec §7 step 2 "user accepts/edits") commits its source-marker edits without
         *     a separate PATCH route. When ``raw_text`` is omitted or null, the route reads
         *     the stored copy and does not modify it — backwards-compatible.
         */
        StructureRequestBody: {
            /** Raw Text */
            raw_text?: string | null;
        };
        /**
         * StructureResponse
         * @description What the structure route returns once the outline is persisted.
         */
        StructureResponse: {
            /**
             * Story Id
             * Format: uuid
             */
            story_id: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "auto" | "manual" | "hybrid";
            /** Chapter Count */
            chapter_count: number;
            /** Scene Count */
            scene_count: number;
            /** Paragraph Count */
            paragraph_count: number;
        };
        /**
         * TaskTypeUsage
         * @description Today's call count and USD spend for one task type (status dashboard).
         */
        TaskTypeUsage: {
            /** Task Type */
            task_type: string;
            /** Calls */
            calls: number;
            /** Cost Usd */
            cost_usd: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    upload_story_stories_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_story_stories_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoryUploadResponse"];
                };
            };
            /** @description Uploaded file is empty or unparseable. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description File exceeds the maximum upload size. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unsupported file extension or content type mismatch. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    structure_story_stories__story_id__structure_post: {
        parameters: {
            query: {
                mode: "auto" | "manual" | "hybrid";
            };
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["StructureRequestBody"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructureResponse"];
                };
            };
            /** @description Story not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Story already has a structure (re-structure is refused). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Chunking agent failed — LLM unreachable or unusable output after retries. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    extract_story_stories__story_id__extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractResponse"];
                };
            };
            /** @description Budget/quota pause hit mid-batch; partial progress, re-POST to resume. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractResponse"];
                };
            };
            /** @description Story not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Extraction failed — LLM unreachable or unusable output after retries. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A data store (Postgres/Neo4j) is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_story_graph_stories__story_id__graph_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphResponse"];
                };
            };
            /** @description Story not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_entities_route_stories__story_id__entities_get: {
        parameters: {
            query?: {
                q?: string;
            };
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntitySearchResponse"];
                };
            };
            /** @description Story not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_candidates_stories__story_id__candidates_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidatesResponse"];
                };
            };
            /** @description Story not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description The staging store is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    accept_candidate_stories__story_id__candidates__candidate_id__accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
                candidate_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AcceptRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponse"];
                };
            };
            /** @description Story or candidate not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Merge target no longer exists (stale). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description A data store is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    reject_candidate_stories__story_id__candidates__candidate_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
                candidate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponse"];
                };
            };
            /** @description Story or candidate not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description The staging store is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    llm_status_llm_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmStatusResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
