/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/stories/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Story */
        post: operations["upload_story_stories_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stories/{story_id}/structure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Structure Story
         * @description Build the document tree for a story (spec §7 step 2) and persist it.
         *
         *     Reads the story's stored raw text — which already carries the author's
         *     `##` / `###` anchors for manual/hybrid — builds the outline in the chosen
         *     mode, and inserts chapters → scenes → paragraphs. One-shot: the accept/edit
         *     loop is the frontend's job (Session 6). Re-structuring is refused (409) rather
         *     than silently appending a second tree.
         *
         *     Locking strategy: the outline is built *without* holding a DB write lock,
         *     because auto/hybrid awaits an LLM call that can take seconds. The story row
         *     is then `SELECT ... FOR UPDATE`-locked only for the small write window —
         *     re-check `list_chapters` under the lock, then insert. Two concurrent POSTs
         *     serialize on the lock: the second sees the persisted tree and 409s instead
         *     of duplicating.
         */
        post: operations["structure_story_stories__story_id__structure_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stories/{story_id}/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract Story
         * @description Extract entities/relations from a story's paragraphs into the graph (spec §9 M2).
         *
         *     Walks every persisted paragraph, runs the ExtractionAgent, and writes fresh graph
         *     nodes/edges + `entity_mentions` with **no dedupe** (INV-8 — every candidate a new
         *     node). The batch is resumable: if the router pauses on budget/quota, the run stops
         *     with `paused=true` (HTTP 202) and a re-POST continues from the last-done paragraph
         *     (the committed mentions are the checkpoint). Budget/quota are therefore *not* HTTP
         *     errors here by design (OQ-2); only a hard agent failure maps to 502.
         */
        post: operations["extract_story_stories__story_id__extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/llm/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Llm Status
         * @description Today's spend, GPU-seconds, and per-task-type breakdown against the cap.
         */
        get: operations["llm_status_llm_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe used by the frontend smoke check and by CI.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_story_stories_upload_post */
        Body_upload_story_stories_upload_post: {
            /** File */
            file: string;
        };
        /**
         * ErrorResponse
         * @description Shape FastAPI's ``HTTPException`` produces — declared so the OpenAPI
         *     schema names every non-2xx response the routes can return, instead of just
         *     success + the auto-added 422 validation error. Without this, the generated
         *     TypeScript client (`frontend/src/lib/api/schema.d.ts`) can't model expected
         *     outcomes like 404 / 409 / 502 — leaving frontend error handling untyped.
         */
        ErrorResponse: {
            /** Detail */
            detail: string;
        };
        /**
         * ExtractResponse
         * @description Progress of an extraction run over a story's paragraphs (spec §9 M2).
         *
         *     `paused` is the completion signal — true when the run stopped at the budget/quota
         *     pause-and-ask (HTTP 202, partial progress), false when it finished (HTTP 200).
         *     `paragraphs_done` counts paragraphs that carry a mention — the resumable
         *     checkpoint — so a re-POST resumes from the first not-done paragraph.
         */
        ExtractResponse: {
            /**
             * Story Id
             * Format: uuid
             */
            story_id: string;
            /** Paragraphs Total */
            paragraphs_total: number;
            /** Paragraphs Done */
            paragraphs_done: number;
            /** Entities Written */
            entities_written: number;
            /** Relations Written */
            relations_written: number;
            /** Paused */
            paused: boolean;
            /** Pause Reason */
            pause_reason: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LlmStatusResponse
         * @description Budget + today's usage for the agent-activity panel.
         */
        LlmStatusResponse: {
            /** Daily Budget Usd */
            daily_budget_usd: number;
            /** Spent Today Usd */
            spent_today_usd: number;
            /** Remaining Usd */
            remaining_usd: number;
            /** Gpu Seconds Today */
            gpu_seconds_today: number;
            /** Calls Today */
            calls_today: number;
            /** By Task Type */
            by_task_type: components["schemas"]["TaskTypeUsage"][];
        };
        /**
         * StoryUploadResponse
         * @description What the upload route returns once a story is persisted.
         *
         *     ``raw_text`` is echoed back so the frontend's manual-mode editor (spec §7
         *     step 2) has the parsed source to edit. The browser doesn't reliably parse
         *     .docx itself, so the upload response is the cheapest place to surface it;
         *     avoids a follow-up GET /stories/{id} round-trip that doesn't exist yet.
         */
        StoryUploadResponse: {
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /**
             * Story Id
             * Format: uuid
             */
            story_id: string;
            /** Title */
            title: string;
            /** Language */
            language: string;
            /** Paragraph Count */
            paragraph_count: number;
            /** Raw Text */
            raw_text: string;
        };
        /**
         * StructureRequestBody
         * @description Optional body for ``POST /stories/{id}/structure``.
         *
         *     When ``raw_text`` is provided, the route parses the outline from this payload
         *     instead of the story's stored copy AND persists it back to ``stories.raw_text``
         *     in the same transaction. This is how the frontend manual-mode editor
         *     (spec §7 step 2 "user accepts/edits") commits its source-marker edits without
         *     a separate PATCH route. When ``raw_text`` is omitted or null, the route reads
         *     the stored copy and does not modify it — backwards-compatible.
         */
        StructureRequestBody: {
            /** Raw Text */
            raw_text?: string | null;
        };
        /**
         * StructureResponse
         * @description What the structure route returns once the outline is persisted.
         */
        StructureResponse: {
            /**
             * Story Id
             * Format: uuid
             */
            story_id: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "auto" | "manual" | "hybrid";
            /** Chapter Count */
            chapter_count: number;
            /** Scene Count */
            scene_count: number;
            /** Paragraph Count */
            paragraph_count: number;
        };
        /**
         * TaskTypeUsage
         * @description Today's call count and USD spend for one task type (status dashboard).
         */
        TaskTypeUsage: {
            /** Task Type */
            task_type: string;
            /** Calls */
            calls: number;
            /** Cost Usd */
            cost_usd: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    upload_story_stories_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_story_stories_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoryUploadResponse"];
                };
            };
            /** @description Uploaded file is empty or unparseable. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description File exceeds the maximum upload size. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unsupported file extension or content type mismatch. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    structure_story_stories__story_id__structure_post: {
        parameters: {
            query: {
                mode: "auto" | "manual" | "hybrid";
            };
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["StructureRequestBody"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructureResponse"];
                };
            };
            /** @description Story not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Story already has a structure (re-structure is refused). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Chunking agent failed — LLM unreachable or unusable output after retries. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    extract_story_stories__story_id__extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractResponse"];
                };
            };
            /** @description Budget/quota pause hit mid-batch; partial progress, re-POST to resume. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractResponse"];
                };
            };
            /** @description Story not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Extraction failed — LLM unreachable or unusable output after retries. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    llm_status_llm_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmStatusResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
