/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/stories/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Story */
        post: operations["upload_story_stories_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stories/{story_id}/structure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Structure Story
         * @description Build the document tree for a story (spec §7 step 2) and persist it.
         *
         *     Reads the story's stored raw text — which already carries the author's
         *     `##` / `###` anchors for manual/hybrid — builds the outline in the chosen
         *     mode, and inserts chapters → scenes → paragraphs. One-shot: the accept/edit
         *     loop is the frontend's job (Session 6). Re-structuring is refused (409) rather
         *     than silently appending a second tree.
         *
         *     Locking strategy: the outline is built *without* holding a DB write lock,
         *     because auto/hybrid awaits an LLM call that can take seconds. The story row
         *     is then `SELECT ... FOR UPDATE`-locked only for the small write window —
         *     re-check `list_chapters` under the lock, then insert. Two concurrent POSTs
         *     serialize on the lock: the second sees the persisted tree and 409s instead
         *     of duplicating.
         */
        post: operations["structure_story_stories__story_id__structure_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stories/{story_id}/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract Story
         * @description Extract + stage a story's candidates through the §3.3 cascade (spec §9 M3).
         *
         *     Walks every persisted paragraph, runs the ExtractionAgent, then the cascade, and *stages*
         *     each candidate with its proposal (NEW vs MERGE) — writing **nothing** to the graph
         *     (intercept-before-write, INV-9). The graph is written only when a human accepts at the
         *     review queue (`POST …/candidates/{id}/accept`, INV-1). The batch is resumable: if the
         *     router pauses on budget/quota, the run stops with `paused=true` (HTTP 202) and a re-POST
         *     continues from the first un-staged paragraph. Budget/quota are therefore *not* HTTP errors
         *     here by design (OQ-2); a hard agent failure maps to 502, a store outage to 503.
         */
        post: operations["extract_story_stories__story_id__extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stories/{story_id}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Story Graph
         * @description The story's entity graph for the read-only viewer (spec §3.4).
         *
         *     The graph is keyed by *project* (entities carry `project_id`, the §6.4
         *     multi-tenancy seam), so the route resolves the story to its project and returns
         *     that project's nodes/edges. No dedupe through M2 (INV-8) — the viewer renders
         *     whatever was written, duplicates and all, which is exactly the problem M3 solves.
         */
        get: operations["get_story_graph_stories__story_id__graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stories/{story_id}/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Entities Route
         * @description Search the project's accepted entities for the Stage-4 *manual handpick* (spec §3.3).
         *
         *     The reviewer can search **all** accepted entities in the project and pick any one as the
         *     merge target — the safety net for a true duplicate the deterministic cascade missed (a
         *     nickname embeddings don't catch, a name scoring just under threshold). Scope is the
         *     story's **project** (the §6.4 tenancy key); cross-project / "whole world" search is
         *     deferred with the §3.4 graph.
         *
         *     The query `q` is ranked **in Python** with the same RapidFuzz signal the matcher uses
         *     (`search_entities` over `canonical_name` + aliases) — so the human's search ≈ the
         *     machine's match — and so `q` **never reaches Cypher**: the only graph query
         *     (`list_entities`) is parameterised by `project_id` alone. Blank `q` → no results.
         */
        get: operations["search_entities_route_stories__story_id__entities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stories/{story_id}/reader": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Story Reader
         * @description The story text with accepted entities highlighted inline (spec §3.5, M4.S1).
         *
         *     A read-only projection of the accepted graph onto the prose. Paragraphs + their mentions
         *     are *story*-scoped; the entity catalog is read *project*-scoped (the §6.4 tenancy key, the
         *     same seam as `/graph` and `/entities`) — correct while one story = one project, and the
         *     natural first home of the §3.4 per-story filter when multi-story lands. Each paragraph's
         *     mentioned entities are resolved to character ranges by render-time search over their surface
         *     forms (`resolve_highlights`); an entity whose forms don't occur is omitted (fail-closed), and
         *     only entities that actually appear are advertised in the tooltip catalog.
         */
        get: operations["get_story_reader_stories__story_id__reader_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stories/{story_id}/entities/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Entity Detail
         * @description An accepted entity's details + properties + 1-hop local graph (spec §3.4/§3.5, M4.S2a).
         *
         *     The read behind the reader side panel (DM-SP-1a — a focused per-entity endpoint): resolve the
         *     story → its project (the §6.4 tenancy key, the same seam as `/graph` and `/reader`), confirm
         *     the entity belongs to that project (else 404 — never leak another project's node), then return
         *     its display fields + `properties` + the `build_ego_graph` projection of its
         *     `get_neighbourhood` (DM-SP-2: strict 1-hop, entity-incident edges, self-loops dropped). A
         *     read-only projection — INV-1/INV-9 untouched, no LLM call.
         */
        get: operations["get_entity_detail_stories__story_id__entities__entity_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Entity Route
         * @description Delete an accepted entity, its relations, and its text occurrences (spec §3.4, M4.S3b-be2,
         *     DM-S3b-5).
         *
         *     A human-reached graph write (INV-9 as reworded — ADR 0006/0007): a real `DETACH DELETE` plus a
         *     full-snapshot before-image (node fields + incident edges + mentions) recorded as one grouped,
         *     **reversible** operation (INV-3) so undo can restore it. 404s if the entity isn't accepted in
         *     this project. The side panel invalidates + refetches the reader/graph bundle (DM-S3a-4).
         */
        delete: operations["delete_entity_route_stories__story_id__entities__entity_id__delete"];
        options?: never;
        head?: never;
        /**
         * Edit Entity Route
         * @description Edit an accepted entity's name/aliases/type/`properties` (spec §3.4, DM-S3a-1).
         *
         *     A human-reached graph write (INV-9 as reworded — ADR 0006): re-reads under the project's
         *     tenancy key, validates + merges the patch, writes the node, and records a before→after
         *     edit-evidence row (INV-3, DM-S3a-2). A blank name/type is rejected (400). `properties` stays
         *     open (INV-4). A corrected name/alias re-highlights in the reader for free (render-time search,
         *     DM-S3a-4); the panel invalidates + refetches the detail bundle.
         */
        patch: operations["edit_entity_route_stories__story_id__entities__entity_id__patch"];
        trace?: never;
    };
    "/stories/{story_id}/relations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Relations
         * @description The committable relations for a story (spec §3.3's 5th Stage-4 action).
         *
         *     A relation is committable once **both** surface endpoints resolve to entities the human has
         *     already accepted in that paragraph; relations with a held/unaccepted endpoint or a self-loop
         *     are excluded. The edge is written only on an explicit `decide` (INV-1/INV-9 — the human gate).
         */
        get: operations["list_relations_stories__story_id__relations_get"];
        put?: never;
        /**
         * Add Relation Route
         * @description Add a relation between two accepted entities (spec §3.4, DM-S3a-3, direct edge-writer).
         *
         *     Both endpoints must already be accepted in this project (else 404). A duplicate add MERGEs
         *     onto the existing edge and is reported via `merged_into_existing` rather than erroring; a
         *     manual self-loop is allowed. Records a before→after edit-evidence row (INV-3, DM-S3a-2).
         */
        post: operations["add_relation_route_stories__story_id__relations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stories/{story_id}/relations/{edge_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove Relation Route
         * @description Remove a relation edge (spec §3.4, DM-S3a-3). 404s if the edge isn't in this project (a
         *     stale double-remove); records the before-image for undo (INV-3, DM-S3a-2).
         */
        delete: operations["remove_relation_route_stories__story_id__relations__edge_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stories/{story_id}/entities/{entity_id}/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Merge Entity Route
         * @description Merge entity B (`entity_id`, absorbed) into survivor A (`target_entity_id`) — spec §3.4,
         *     DM-S3b-1/2/3/4.
         *
         *     A human-reached graph write (INV-9 as reworded — ADR 0006/0007): folds B's aliases/properties
         *     into A (author-resolved conflicts), re-points every edge and mention incident to B onto A, then
         *     deletes B — recording the whole fan-out as one **grouped, reversible** operation (INV-3,
         *     DM-S3b-1) so undo can reverse it. Both entities must be accepted in this project (else 404); a
         *     self-merge is rejected (409); an unresolved property conflict is rejected (400). The side panel
         *     invalidates + refetches the reader/graph/detail bundle (DM-S3a-4).
         */
        post: operations["merge_entity_route_stories__story_id__entities__entity_id__merge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stories/{story_id}/graph-edits/undo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Undo Last Route
         * @description Reverse the newest not-yet-undone graph operation in this story's project — the general undo
         *     executor (spec §10 q2 / §11 / §4.3, M4.S3b-be2, DM-S3b-1).
         *
         *     Pops the top of the per-project undo stack and replays each change's inverse in reverse order
         *     (INV-3), then marks the operation `undone`. With `?preview=true` it returns *what would be
         *     reversed* without acting, so the UI can confirm first (DM-S3b-1, see-what-I-undo). 404 when the
         *     stack is empty; 409 when the graph drifted since the operation (a lost update in reverse —
         *     undoing would clobber a newer edit, so it refuses rather than overwrite).
         */
        post: operations["undo_last_route_stories__story_id__graph_edits_undo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stories/{story_id}/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Candidates
         * @description The pending review queue for a story (spec §3.3 Stage 4) — candidates awaiting a human.
         */
        get: operations["list_candidates_stories__story_id__candidates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stories/{story_id}/candidates/{candidate_id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept Candidate
         * @description Commit a staged candidate to the graph — create a new entity or merge (spec §7 step 7).
         *
         *     This is the **only** graph-writing path (INV-1): the machine proposed, the human commits.
         */
        post: operations["accept_candidate_stories__story_id__candidates__candidate_id__accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stories/{story_id}/candidates/{candidate_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject Candidate
         * @description Reject a staged candidate — nothing enters the graph; the rejection is recorded.
         *
         *     The rejection is stored as evidence so a future matcher can consult it and not re-pester
         *     the author (DM-rej); that consult is not built in S4a.
         */
        post: operations["reject_candidate_stories__story_id__candidates__candidate_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stories/{story_id}/relations/{relation_id}/decide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decide Relation
         * @description Commit (write the edge) or reject a staged relation under the human gate (spec §3.3).
         *
         *     The **only** edge-writing path (INV-1/INV-9). Commit re-resolves both endpoints (TOCTOU)
         *     and writes the edge idempotently; an endpoint that no longer resolves, or a self-loop,
         *     yields 409 with nothing written.
         */
        post: operations["decide_relation_stories__story_id__relations__relation_id__decide_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/llm/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Llm Status
         * @description Today's spend, GPU-seconds, per-task-type breakdown, and the most recent call.
         */
        get: operations["llm_status_llm_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe used by the frontend smoke check and by CI.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AcceptRequest
         * @description The reviewer's decision (spec §3.3 Stage 4). All optional — defaults to the proposal.
         *
         *     `action` overrides the cascade's proposal (accept-as-merge / accept-as-create);
         *     `target_entity_id` retargets a merge (change-target); `custom_type` sets a type on create.
         */
        AcceptRequest: {
            /** Action */
            action?: ("create" | "merge") | null;
            /** Target Entity Id */
            target_entity_id?: string | null;
            /** Custom Type */
            custom_type?: string | null;
        };
        /**
         * AddRelationRequest
         * @description Add a relation between two accepted entities (DM-S3a-3). A self-loop (subject == object)
         *     is allowed — a manual one is intentional. Re-predicate is a remove + add, client-side.
         */
        AddRelationRequest: {
            /**
             * Subject Id
             * Format: uuid
             */
            subject_id: string;
            /** Predicate */
            predicate: string;
            /**
             * Object Id
             * Format: uuid
             */
            object_id: string;
        };
        /** Body_upload_story_stories_upload_post */
        Body_upload_story_stories_upload_post: {
            /** File */
            file: string;
        };
        /**
         * CandidateView
         * @description One staged candidate for the §3.3 Stage-4 review queue (the render set S4b consumes).
         *
         *     Carries the quote/context (±200 chars), the cascade's NEW-vs-MERGE proposal + the stage it
         *     reached, the judge's reasoning (if Stage 3 ran), and the top-3 alternative entities the
         *     reviewer can retarget to. Persistence-only fields (the vector, project/story ids) are omitted.
         */
        CandidateView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Paragraph Id
             * Format: uuid
             */
            paragraph_id: string;
            /** Candidate Name */
            candidate_name: string;
            /** Type */
            type: string;
            /** Context */
            context: string;
            /**
             * Proposal
             * @enum {string}
             */
            proposal: "new" | "merge";
            /** Target Entity Id */
            target_entity_id: string | null;
            /** Stage Reached */
            stage_reached: number;
            /** Confidence */
            confidence: number | null;
            /** Reasoning */
            reasoning: string | null;
            /** Alternatives */
            alternatives: {
                [key: string]: unknown;
            }[];
        };
        /**
         * CandidatesResponse
         * @description A story's pending review queue.
         */
        CandidatesResponse: {
            /** Candidates */
            candidates: components["schemas"]["CandidateView"][];
        };
        /**
         * DecideRelationRequest
         * @description The reviewer's relation decision: commit the edge, or reject the relation.
         */
        DecideRelationRequest: {
            /**
             * Action
             * @enum {string}
             */
            action: "commit" | "reject";
        };
        /**
         * EgoEdge
         * @description One relation edge incident to the focal entity, oriented relative to it.
         *
         *     `direction` is `out` when the focal entity is the relation's subject (focal→neighbour) and
         *     `in` when it is the object (neighbour→focal); `neighbour_id` is the entity on the far end.
         */
        EgoEdge: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Type */
            type: string;
            /**
             * Direction
             * @enum {string}
             */
            direction: "out" | "in";
            /**
             * Neighbour Id
             * Format: uuid
             */
            neighbour_id: string;
            /** Confidence */
            confidence: number;
        };
        /**
         * EgoGraph
         * @description The focal entity's 1-hop neighbourhood: its direct neighbours + the edges touching it.
         */
        EgoGraph: {
            /** Neighbours */
            neighbours?: components["schemas"]["EgoNeighbour"][];
            /** Edges */
            edges?: components["schemas"]["EgoEdge"][];
        };
        /**
         * EgoNeighbour
         * @description One directly-connected entity in the focal node's 1-hop neighbourhood (display subset).
         *
         *     The same colour-by-type/name fields the §3.4 graph node carries, so the panel's mini-graph
         *     can render a neighbour without a second lookup. `type` is open-world (INV-4).
         */
        EgoNeighbour: {
            /**
             * Entity Id
             * Format: uuid
             */
            entity_id: string;
            /** Type */
            type: string;
            /** Canonical Name Pl */
            canonical_name_pl?: string | null;
            /** Canonical Name En */
            canonical_name_en?: string | null;
            /** Aliases */
            aliases?: string[];
        };
        /**
         * EntityDetailResponse
         * @description One accepted entity's detail bundle for the reader side panel (spec §3.4/§3.5, M4.S2a).
         *
         *     The two things the reader page doesn't already hold: the entity's free-form `properties`
         *     (surfaced by no other endpoint) and its 1-hop `ego_graph` (the "local graph around that
         *     entity", §3.5). Name/type/aliases are included so the panel is self-contained. Occurrences
         *     are derived frontend-side from the reader's already-rendered highlights (DM-SP-3), so they
         *     are not repeated here. Read-only — editing properties/relations is the next M4 slice.
         */
        EntityDetailResponse: {
            /**
             * Entity Id
             * Format: uuid
             */
            entity_id: string;
            /** Canonical Name */
            canonical_name: string;
            /** Language */
            language: string;
            /** Type */
            type: string;
            /** Aliases */
            aliases: string[];
            /** Properties */
            properties: {
                [key: string]: unknown;
            };
            ego_graph: components["schemas"]["EgoGraph"];
        };
        /**
         * EntityEditPatch
         * @description A partial edit of a committed entity (M4.S3a). Every field optional; an unset field
         *     (`None`) leaves it unchanged. `properties`, when set, replaces the whole map and stays open
         *     per INV-4 (pydantic guarantees it is a JSON object; values keep their type — DM-S3a-5).
         */
        EntityEditPatch: {
            /** Canonical Name Pl */
            canonical_name_pl?: string | null;
            /** Canonical Name En */
            canonical_name_en?: string | null;
            /** Type */
            type?: string | null;
            /** Aliases */
            aliases?: string[] | null;
            /** Properties */
            properties?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * EntityEditResponse
         * @description The edited entity's display fields after a successful PATCH (M4.S3a). The side panel
         *     invalidates + refetches the full detail bundle (ego-graph, occurrences) via the GET endpoint
         *     (DM-S3a-4), so this slim shape carries only what the edit changed.
         */
        EntityEditResponse: {
            /**
             * Entity Id
             * Format: uuid
             */
            entity_id: string;
            /** Canonical Name */
            canonical_name: string;
            /** Type */
            type: string;
            /** Aliases */
            aliases: string[];
            /** Properties */
            properties: {
                [key: string]: unknown;
            };
        };
        /**
         * EntitySearchResponse
         * @description The handpick search hits, ranked best-first (spec §3.3 *Manual handpick*).
         */
        EntitySearchResponse: {
            /** Entities */
            entities: components["schemas"]["EntitySearchResult"][];
        };
        /**
         * EntitySearchResult
         * @description One accepted entity matched by the handpick search — the picker's row (M3.S4d).
         *
         *     Mirrors the review card's existing top-3 *alternative* shape (`entity_id` +
         *     `canonical_name` + `score`) so a picked search result feeds the same merge-accept path,
         *     plus `type` (to disambiguate same-named entities) and `aliases` (so the card can show
         *     *why* it matched). `canonical_name` is the project-language-resolved name the matcher
         *     ranks on, so the human's search reads the same name the machine matched.
         */
        EntitySearchResult: {
            /**
             * Entity Id
             * Format: uuid
             */
            entity_id: string;
            /** Canonical Name */
            canonical_name: string;
            /** Type */
            type: string;
            /** Score */
            score: number;
            /** Aliases */
            aliases: string[];
        };
        /**
         * ErrorResponse
         * @description Shape FastAPI's ``HTTPException`` produces — declared so the OpenAPI
         *     schema names every non-2xx response the routes can return, instead of just
         *     success + the auto-added 422 validation error. Without this, the generated
         *     TypeScript client (`frontend/src/lib/api/schema.d.ts`) can't model expected
         *     outcomes like 404 / 409 / 502 — leaving frontend error handling untyped.
         */
        ErrorResponse: {
            /** Detail */
            detail: string;
        };
        /**
         * ExtractResponse
         * @description Progress of an extraction run over a story's paragraphs (spec §9 M3).
         *
         *     Under intercept-before-write extraction *stages* candidates (it does not write the graph),
         *     so the count is `candidates_staged`, not entities/relations written. `paused` is the
         *     completion signal — true when the run stopped at the budget/quota pause-and-ask (HTTP 202,
         *     partial progress), false when it finished (HTTP 200). `paragraphs_done` counts paragraphs
         *     already staged (the resume checkpoint), so a re-POST resumes from the first not-done one.
         */
        ExtractResponse: {
            /**
             * Story Id
             * Format: uuid
             */
            story_id: string;
            /** Paragraphs Total */
            paragraphs_total: number;
            /** Paragraphs Done */
            paragraphs_done: number;
            /** Candidates Staged */
            candidates_staged: number;
            /** Paused */
            paused: boolean;
            /** Pause Reason */
            pause_reason: string | null;
        };
        /**
         * GraphEdge
         * @description One typed, directed relation for the viewer (edge label = `type`, §3.4).
         */
        GraphEdge: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Type */
            type: string;
            /**
             * Subject Id
             * Format: uuid
             */
            subject_id: string;
            /**
             * Object Id
             * Format: uuid
             */
            object_id: string;
            /** Confidence */
            confidence: number;
        };
        /**
         * GraphNode
         * @description One entity node for the §3.4 viewer — the display subset of `GraphEntity`.
         *
         *     Persistence-only fields (`properties`, `embedding`, `project_id`, `world_id`)
         *     are omitted: the read-only M2 viewer colours by `type`, labels by canonical
         *     name/aliases, and links each node to its first occurrence paragraph.
         */
        GraphNode: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Type */
            type: string;
            /** Canonical Name Pl */
            canonical_name_pl: string | null;
            /** Canonical Name En */
            canonical_name_en: string | null;
            /** Aliases */
            aliases: string[];
            /** First Seen Paragraph Id */
            first_seen_paragraph_id: string | null;
        };
        /**
         * GraphResponse
         * @description The story's knowledge graph as nodes + edges for the viewer.
         */
        GraphResponse: {
            /** Nodes */
            nodes: components["schemas"]["GraphNode"][];
            /** Edges */
            edges: components["schemas"]["GraphEdge"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LastCall
         * @description The most recently recorded call, for the §8.5 agent-activity panel ("which
         *     agent ran most recently, which model/tier, latency, cost"). System-derived,
         *     read straight from the latest ledger row; `created_at` is the store's clock.
         */
        LastCall: {
            /** Task Type */
            task_type: string;
            /**
             * Tier
             * @enum {string}
             */
            tier: "local_small" | "cloud_free" | "cloud_strong";
            /** Provider */
            provider: string;
            /** Model */
            model: string | null;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "success" | "refusal" | "failure";
            /** Latency Ms */
            latency_ms: number | null;
            /** Cost Estimate */
            cost_estimate: number | null;
            /** Gpu Seconds */
            gpu_seconds: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * LlmStatusResponse
         * @description Budget + today's usage + the most recent call, for the agent-activity panel.
         */
        LlmStatusResponse: {
            /** Daily Budget Usd */
            daily_budget_usd: number;
            /** Spent Today Usd */
            spent_today_usd: number;
            /** Remaining Usd */
            remaining_usd: number;
            /** Gpu Seconds Today */
            gpu_seconds_today: number;
            /** Calls Today */
            calls_today: number;
            /** By Task Type */
            by_task_type: components["schemas"]["TaskTypeUsage"][];
            last_call: components["schemas"]["LastCall"] | null;
        };
        /**
         * MergeRequest
         * @description Merge entity B (the path `entity_id`, absorbed) into survivor A (`target_entity_id`),
         *     M4.S3b (DM-S3b-2/8). `resolved_properties` carries the author's chosen value for every
         *     property key the two entities set differently — by-hand conflict resolution; a missing one is
         *     rejected (400). Non-conflicting keys union automatically, so they need not be listed.
         */
        MergeRequest: {
            /**
             * Target Entity Id
             * Format: uuid
             */
            target_entity_id: string;
            /**
             * Resolved Properties
             * @default {}
             */
            resolved_properties: {
                [key: string]: unknown;
            };
        };
        /**
         * MergeSummaryResponse
         * @description Outcome of a merge: the survivor's id + the counts the side panel reports — how many edges
         *     were re-pointed, how many MERGE-folded (multiplicity lost, surfaced not silent, DM-S3b-3), how
         *     many self-loops were dropped, and how many mentions moved onto the survivor.
         */
        MergeSummaryResponse: {
            /**
             * Survivor Entity Id
             * Format: uuid
             */
            survivor_entity_id: string;
            /** Repointed Count */
            repointed_count: number;
            /** Folded Count */
            folded_count: number;
            /** Self Loops Dropped */
            self_loops_dropped: number;
            /** Mentions Repointed */
            mentions_repointed: number;
        };
        /**
         * ReaderEntity
         * @description Tooltip data for an entity that appears in the reader (DM-IH-8: name + type + aliases).
         */
        ReaderEntity: {
            /**
             * Entity Id
             * Format: uuid
             */
            entity_id: string;
            /** Canonical Name */
            canonical_name: string;
            /** Type */
            type: string;
            /** Aliases */
            aliases: string[];
        };
        /**
         * ReaderHighlight
         * @description One resolved highlight range `[start, end)` within a paragraph (spec §3.5).
         */
        ReaderHighlight: {
            /** Start */
            start: number;
            /** End */
            end: number;
            /**
             * Entity Id
             * Format: uuid
             */
            entity_id: string;
            /** Type */
            type: string;
        };
        /**
         * ReaderParagraph
         * @description A paragraph, in document order, with its resolved highlight ranges over `text`.
         */
        ReaderParagraph: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Text */
            text: string;
            /** Highlights */
            highlights: components["schemas"]["ReaderHighlight"][];
        };
        /**
         * ReaderResponse
         * @description The story's text with inline highlights + a catalog of the entities that appeared.
         */
        ReaderResponse: {
            /** Paragraphs */
            paragraphs: components["schemas"]["ReaderParagraph"][];
            /** Entities */
            entities: components["schemas"]["ReaderEntity"][];
        };
        /**
         * RelationDecisionResponse
         * @description Outcome of a relation decision: the terminal status + the committed edge id (if any).
         */
        RelationDecisionResponse: {
            /**
             * Relation Id
             * Format: uuid
             */
            relation_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "staged" | "written" | "rejected";
            /** Edge Id */
            edge_id: string | null;
            /** Already Decided */
            already_decided: boolean;
        };
        /**
         * RelationEditResponse
         * @description Outcome of adding a relation: the edge id + whether the add folded onto an edge that
         *     already existed (the duplicate/re-predicate collision the UI warns on, DM-S3a-3).
         */
        RelationEditResponse: {
            /**
             * Edge Id
             * Format: uuid
             */
            edge_id: string;
            /** Merged Into Existing */
            merged_into_existing: boolean;
        };
        /**
         * RelationView
         * @description One committable relation for the §3.3 5th human action ("decide on relations").
         *
         *     Carries the surface triple + the cascade's confidence and the entity ids both endpoints
         *     currently resolve to (committed entities in the same paragraph). The UI (S4f) renders the
         *     surface strings and can resolve names from the resolved ids; persistence-only fields are
         *     omitted.
         */
        RelationView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Paragraph Id
             * Format: uuid
             */
            paragraph_id: string;
            /** Subject */
            subject: string;
            /** Predicate */
            predicate: string;
            /** Object */
            object: string;
            /** Confidence */
            confidence: number | null;
            /**
             * Subject Entity Id
             * Format: uuid
             */
            subject_entity_id: string;
            /**
             * Object Entity Id
             * Format: uuid
             */
            object_entity_id: string;
        };
        /**
         * RelationsResponse
         * @description A story's committable relations (both endpoints resolved) — the decide queue.
         */
        RelationsResponse: {
            /** Relations */
            relations: components["schemas"]["RelationView"][];
        };
        /**
         * ReviewResponse
         * @description Outcome of an accept/reject: the committed entity (if any) + the terminal status.
         */
        ReviewResponse: {
            /**
             * Candidate Id
             * Format: uuid
             */
            candidate_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "created" | "merged" | "rejected";
            /** Entity Id */
            entity_id: string | null;
            /** Already Decided */
            already_decided: boolean;
        };
        /**
         * StoryUploadResponse
         * @description What the upload route returns once a story is persisted.
         *
         *     ``raw_text`` is echoed back so the frontend's manual-mode editor (spec §7
         *     step 2) has the parsed source to edit. The browser doesn't reliably parse
         *     .docx itself, so the upload response is the cheapest place to surface it;
         *     avoids a follow-up GET /stories/{id} round-trip that doesn't exist yet.
         */
        StoryUploadResponse: {
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /**
             * Story Id
             * Format: uuid
             */
            story_id: string;
            /** Title */
            title: string;
            /** Language */
            language: string;
            /** Paragraph Count */
            paragraph_count: number;
            /** Raw Text */
            raw_text: string;
        };
        /**
         * StructureRequestBody
         * @description Optional body for ``POST /stories/{id}/structure``.
         *
         *     When ``raw_text`` is provided, the route parses the outline from this payload
         *     instead of the story's stored copy AND persists it back to ``stories.raw_text``
         *     in the same transaction. This is how the frontend manual-mode editor
         *     (spec §7 step 2 "user accepts/edits") commits its source-marker edits without
         *     a separate PATCH route. When ``raw_text`` is omitted or null, the route reads
         *     the stored copy and does not modify it — backwards-compatible.
         */
        StructureRequestBody: {
            /** Raw Text */
            raw_text?: string | null;
        };
        /**
         * StructureResponse
         * @description What the structure route returns once the outline is persisted.
         */
        StructureResponse: {
            /**
             * Story Id
             * Format: uuid
             */
            story_id: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "auto" | "manual" | "hybrid";
            /** Chapter Count */
            chapter_count: number;
            /** Scene Count */
            scene_count: number;
            /** Paragraph Count */
            paragraph_count: number;
        };
        /**
         * TaskTypeUsage
         * @description Today's call count and USD spend for one task type (status dashboard).
         */
        TaskTypeUsage: {
            /** Task Type */
            task_type: string;
            /** Calls */
            calls: number;
            /** Cost Usd */
            cost_usd: number;
        };
        /**
         * UndoResponse
         * @description What the undo affordance shows (DM-S3b-1, see-what-I-undo). On a real undo `applied` is True
         *     and `description` names what was reversed ("merged Broniek into Bronisław"); with `?preview=true`
         *     `applied` is False and it reports what *would* be reversed without touching the graph.
         */
        UndoResponse: {
            /** Description */
            description: string;
            /** Op Kind */
            op_kind: string;
            /** Applied */
            applied: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    upload_story_stories_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_story_stories_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoryUploadResponse"];
                };
            };
            /** @description Uploaded file is empty or unparseable. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description File exceeds the maximum upload size. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unsupported file extension or content type mismatch. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    structure_story_stories__story_id__structure_post: {
        parameters: {
            query: {
                mode: "auto" | "manual" | "hybrid";
            };
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["StructureRequestBody"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructureResponse"];
                };
            };
            /** @description Story not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Story already has a structure (re-structure is refused). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Chunking agent failed — LLM unreachable or unusable output after retries. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    extract_story_stories__story_id__extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractResponse"];
                };
            };
            /** @description Budget/quota pause hit mid-batch; partial progress, re-POST to resume. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractResponse"];
                };
            };
            /** @description Story not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Extraction failed — LLM unreachable or unusable output after retries. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A data store (Postgres/Neo4j) is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_story_graph_stories__story_id__graph_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphResponse"];
                };
            };
            /** @description Story not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_entities_route_stories__story_id__entities_get: {
        parameters: {
            query?: {
                q?: string;
            };
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntitySearchResponse"];
                };
            };
            /** @description Story not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_story_reader_stories__story_id__reader_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReaderResponse"];
                };
            };
            /** @description Story not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_entity_detail_stories__story_id__entities__entity_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityDetailResponse"];
                };
            };
            /** @description Story or entity not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_entity_route_stories__story_id__entities__entity_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Story or entity not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description A data store is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    edit_entity_route_stories__story_id__entities__entity_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntityEditPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityEditResponse"];
                };
            };
            /** @description The edit is invalid (blank name or type). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Story or entity not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description A data store is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_relations_stories__story_id__relations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationsResponse"];
                };
            };
            /** @description Story not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description The staging store is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    add_relation_route_stories__story_id__relations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddRelationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationEditResponse"];
                };
            };
            /** @description Story or an endpoint entity not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description A data store is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    remove_relation_route_stories__story_id__relations__edge_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
                edge_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Story or relation edge not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description A data store is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    merge_entity_route_stories__story_id__entities__entity_id__merge_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MergeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MergeSummaryResponse"];
                };
            };
            /** @description A property conflict was left unresolved. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Story, the absorbed entity, or the merge target not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Self-merge (absorbed == target). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description A data store is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    undo_last_route_stories__story_id__graph_edits_undo_post: {
        parameters: {
            query?: {
                preview?: boolean;
            };
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UndoResponse"];
                };
            };
            /** @description Story not found, or nothing left to undo. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The graph drifted since; undo refused. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description A data store is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_candidates_stories__story_id__candidates_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidatesResponse"];
                };
            };
            /** @description Story not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description The staging store is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    accept_candidate_stories__story_id__candidates__candidate_id__accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
                candidate_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AcceptRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponse"];
                };
            };
            /** @description Story or candidate not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Merge target no longer exists (stale). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description A data store is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    reject_candidate_stories__story_id__candidates__candidate_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
                candidate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponse"];
                };
            };
            /** @description Story or candidate not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description The staging store is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    decide_relation_stories__story_id__relations__relation_id__decide_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
                relation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecideRelationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationDecisionResponse"];
                };
            };
            /** @description Story or relation not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description An endpoint no longer resolves (stale/held). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description A data store is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    llm_status_llm_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmStatusResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
